//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendeeGuestType
    {
        public int Id { get; set; }
        public int AttendeeID { get; set; }
        public int GuestTypeID { get; set; }
    
        public virtual Attendee Attendee { get; set; }
        public virtual GuestType GuestType { get; set; }
    }
}
