//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Engagement()
        {
            this.EngagementMembers = new HashSet<EngagementMember>();
            this.EngagementNotes = new HashSet<EngagementNote>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> EngageTypeID { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public string Frequency { get; set; }
        public Nullable<double> Visits { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> OnStartDate { get; set; }
        public Nullable<System.DateTime> OnEndDate { get; set; }
        public Nullable<System.DateTime> OffStartDate { get; set; }
        public Nullable<System.DateTime> OffEndDate { get; set; }
        public string ReportModel { get; set; }
        public string Exp { get; set; }
        public Nullable<int> Fee { get; set; }
        public bool AlmReview { get; set; }
        public bool LiquidityReview { get; set; }
        public bool BackTest { get; set; }
        public bool IsReview { get; set; }
        public bool PenTest { get; set; }
        public bool VulA { get; set; }
        public bool LetterMailed { get; set; }
        public bool LetterSigned { get; set; }
        public string Core { get; set; }
        public string Software { get; set; }
        public string NachaFull { get; set; }
        public string Notes { get; set; }
        public Nullable<int> Year { get; set; }
        public string Binder { get; set; }
        public Nullable<System.DateTime> EndFieldDate { get; set; }
        public Nullable<System.DateTime> DateCheckedIn { get; set; }
        public string FileCompletedBy { get; set; }
        public string InitialReviewBy { get; set; }
        public Nullable<System.DateTime> InitialReviewDate { get; set; }
        public bool ReadyForSh { get; set; }
        public string ShReviewBy { get; set; }
        public Nullable<System.DateTime> ShReviewCompleteDate { get; set; }
        public Nullable<System.DateTime> DraftReportDate { get; set; }
        public Nullable<System.DateTime> FinalReportDate { get; set; }
        public bool FileReviewYN { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngagementMember> EngagementMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EngagementNote> EngagementNotes { get; set; }
        public virtual EngageType EngageType { get; set; }
    }
}
