//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngagementMember
    {
        public int Id { get; set; }
        public int EngagementID { get; set; }
        public string UserID { get; set; }
        public int Role { get; set; }
        public bool Leader { get; set; }
    
        public virtual Engagement Engagement { get; set; }
        public virtual User User { get; set; }
    }
}
