//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskNotes = new HashSet<TaskNote>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string AssignedTo { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskNote> TaskNotes { get; set; }
        public virtual User User { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Type Type { get; set; }
    }
}
