//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCG.Models
{
  using System;
  using System.Collections.Generic;

  public partial class User
  {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
      this.Attendees = new HashSet<Attendee>();
      this.Contacts = new HashSet<Contact>();
      this.FavoriteProjects = new HashSet<FavoriteProject>();
      this.KeyPersons = new HashSet<KeyPerson>();
      this.Projects = new HashSet<Project>();
      this.ProjectSchedules = new HashSet<ProjectSchedule>();
      this.SharedProjects = new HashSet<SharedProject>();
      this.TaskNotes = new HashSet<TaskNote>();
      this.Tasks = new HashSet<Task>();
      this.Touches = new HashSet<Touch>();
      this.UserRoles = new HashSet<UserRole>();
      this.Pages = new HashSet<Page>();
      this.EngagementMembers = new HashSet<EngagementMember>();
      this.EngagementNotes = new HashSet<EngagementNote>();
      this.RssFeeds = new HashSet<RssFeed>();
      this.Profiles = new HashSet<Profile>();
      this.MessageOfTheDays = new HashSet<MessageOfTheDay>();
    }

    public string Id { get; set; }
    public string Guid { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string PhoneNumber { get; set; }
    public string Extension { get; set; }
    public Nullable<int> DepartmentID { get; set; }
    public Nullable<int> LocationID { get; set; }
    public bool Status { get; set; }
    public string Title { get; set; }
    public string Family { get; set; }
    public string Bio { get; set; }
    public Nullable<System.DateTime> Birthday { get; set; }
    public bool C0_5 { get; set; }
    public bool C6_12 { get; set; }
    public bool C13_17 { get; set; }
    public bool C18 { get; set; }
    public string FullName { get { return FirstName + " " + LastName; } }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Attendee> Attendees { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Contact> Contacts { get; set; }
    public virtual Department Department { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FavoriteProject> FavoriteProjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<KeyPerson> KeyPersons { get; set; }
    public virtual Location Location { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Project> Projects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProjectSchedule> ProjectSchedules { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SharedProject> SharedProjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TaskNote> TaskNotes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Task> Tasks { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Touch> Touches { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserRole> UserRoles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Page> Pages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EngagementMember> EngagementMembers { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EngagementNote> EngagementNotes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RssFeed> RssFeeds { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Profile> Profiles { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MessageOfTheDay> MessageOfTheDays { get; set; }
  }
}
